### ISSUE TITLE
Improve default tooltip positioning logic

### ISSUE THREAD

**Issue by abought** [statgen/locuszoom#184]
# Purpose
One of the most tedious parts of creating a new data layer is ensuring that tooltips are correctly positioned. In part, this is because each data layer implements its own logic to handle many scenarios.

It should be feasible to generalize the default implementations into a single version that handles common cases, based on the bounding box of the tooltip. 

# TODO
- [x] Default tooltip creation logic
- [x] Fix tooltips on line and orthogonal-line datalayers
- [x] Create a "guides" section for advanced LZ usage; "creating a new datalayer" as first option

**Comment by abought** [comment]
#180
